# ===================================
#  Rest Behavior Config
# ===================================

# Allowed Rest Actions
allowedActions:
  store:

# Model Class name
modelClass: Wwrf\MobileApp\Models\Install
