# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: wwrf.mobileapp::lang.install.label

# Model Form Field configuration
form: $/wwrf/mobileapp/models/install/fields.yaml

# Model Class name
modelClass: Wwrf\MobileApp\Models\Install

# Default redirect location
defaultRedirect: wwrf/mobileapp/installs
