# ===================================
#  Relation Behavior Config
# ===================================

variants:
    label: Variant
    manage:
        form: $/wwrf/mobileapp/models/variant/fields.yaml
        list: $/wwrf/mobileapp/models/variant/columns.yaml
    view:
        list: $/wwrf/mobileapp/models/variant/columns.yaml
        toolbarButtons: create|delete
