# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Platform

# Model Form Field configuration
form: $/wwrf/mobileapp/models/platform/fields.yaml

# Model Class name
modelClass: Wwrf\MobileApp\Models\Platform

# Default redirect location
defaultRedirect: wwrf/mobileapp/platforms

# Create page
create:
    title: Create Platform
    redirect: wwrf/mobileapp/platforms/update/:id
    redirectClose: wwrf/mobileapp/platforms

# Update page
update:
    title: Edit Platform
    redirect: wwrf/mobileapp/platforms
    redirectClose: wwrf/mobileapp/platforms

# Preview page
preview:
    title: Preview Platform
