# ===================================
#  Rest Behavior Config
# ===================================

# Allowed Rest Actions
allowedActions:
  signin:
  register:

# Model Class name
modelClass: Wwrf\MobileApp\Models\Account